##################              IMPORT LIBRARY     #####################
from Figures import Rectangle
from Figures import Triangle
from Figures import Circle
from Figures import Trapezium
from Figures import Square
from Figures import Rhombus
from Figures import Parallelogram
from Figures import Cube
from Figures import Cuboid
from Figures import Cylinder
from Figures import  Cone
from Figures import Frustum_Cone
from Figures import  Sphere
from Figures import H_Sphere
###################               DEFINING MAIN FUNCTION   ############
def main():
    print('##############    RECTANGLE OPERATIONS    ################')
    length = float(input('Enter Length of Rectangle: '))
    bredth = float(input('Enter Breadth of Rectangle : '))
    Rect = Rectangle(length,bredth)
    print('Length of Rectangle = ',Rect.length)
    print('Bredth of Rectangle =', Rect.bredth)
    rect_area = Rect.Area()
    print('Area of the Rectangle is {:.2f}'.format(rect_area))
    rect_perm = Rect.Perimater()
    print('Perimeter of Rectangle is {:.2f}'.format(rect_perm))
    print('##############    TRIANGLE OPERATIONS    ################')
    a = float(input('Enter Side a : '))
    b = float(input('Enter Side b : '))
    c = float(input('Enter Side c : '))
    tri = Triangle(a,b,c)
    print('Side a is {:.2f}\n Side b is {:.2f}\n Side c is {:.2f}'.format(tri.a, tri.b, tri.c))
    tr_area = tri.Area()
    print('Area of the Triangle is {:.2f}'.format(tr_area))
    tr_per = tri.Perimeter()
    print('Perimeter of the Triangle is {:.2f}'.format(tr_per))
    print('##############    CIRCLE OPERATIONS    ################')
    R = float(input('Enter Radius : '))
    Cir = Circle(R)
    print('Radius of Circle is {:.2f}'.format(Cir.R))
    Cr_area = Cir.Area()
    print('Area of the Circle is {:.2f}'.format(Cr_area))
    Cr_Circumference = Cir.Circumference()
    print('Circumference of the Circle is {:.2f}'.format(Cr_Circumference))
    print('##############    TRAPEZIUM OPERATIONS    ################')
    Side1 = float(input('Enter Side1 : '))
    Side2 = float(input('Enter Side2 : '))
    Side3 = float(input('Enter Side 3 : '))
    Side4 = float(input('Enter Side 4 : '))
    Height = float(input('Enter Height : '))
    tra = Trapezium(Side1, Side2,Side3,Side4,Height)
    print('Side 1 is {:.2f}\n Side 2 is {:.2f}\n Side 3 is {:.2f}\n Side 4 is {:.2f}\n Height is {:.2f}'.format(tra.Side1, tra.Side2, tra.Side3, tra.Side4, tra.Height))
    trap_area = tra.Area()
    print('Area of the Trapezium is {:.2f}'.format(trap_area))
    trap_per = tra.Perimeter()
    print('Perimeter of the Trapezium is {:.2f}'.format(trap_per))
    print('##############    SQUARE OPERATIONS    ################')
    Side = float(input('Enter Side of Square: '))
    Sq = Square(Side)
    print('Square Side = ', Sq.Side)
    sq_area = Sq.Area()
    print('Area of the Square is {:.2f}'.format(sq_area))
    sq_perm = Sq.Perimeter()
    print('Perimeter of Square is {:.2f}'.format(sq_perm))
    print('##############    RHOMBUS OPERATIONS    ################')
    Side = float(input('Enter Side of Rhombus: '))
    Diagonal1 = float(input('Enter the Diagonal1 Value :'))
    Diagonal2 = float(input('Enter the Diagnoal2 Value : '))
    Rh = Rhombus(Side,Diagonal1,Diagonal2)
    print('Rhombus Side =', Rh.Side)
    print('Diagnoal1 Value =',Diagonal1)
    print('Diagnoal2 Value =',Diagonal2)
    Rh_area = Rh.Area()
    print('Area of the Rhombus is {:.2f}'.format(Rh_area))
    Rh_perm = Rh.Perimeter()
    print('Perimeter of Rhombus is {:.2f}'.format(Rh_perm))
    print('##############    PARALLELOGRAM OPERATIONS    ################')
    length = float(input('Enter Length of Parallelogram: '))
    bredth = float(input('Enter Breadth of Parallelogram : '))
    Pall = Parallelogram(length, bredth)
    print('length parallelogram = ', Pall.length)
    print('bredth parallelogram =', Pall.bredth)
    pall_area = Pall.Area()
    print('Area of the Parallelogram is {:.2f}'.format(pall_area))
    pall_perm = Pall.Perimater()
    print('Perimeter of Parallelogram is {:.2f}'.format(pall_perm))
    print('##############    CUBE OPERATIONS    ################')
    Side = float(input('Enter Side of Cube: '))
    Cub = Cube(Side)
    print('Side of Cube = ', Cub.Side)
    Cub_Cur_area = Cub.Curved_Area()
    print('Curved Area of the Cube is {:.2f}'.format(Cub_Cur_area))
    Cub_Tot_area = Cub.Total_Area()
    print('Total Surface Area is {:.2f}'.format(Cub_Tot_area))
    Cub_Vol = Cub.Volume()
    print('Volume of Cube is {:.2f}'.format(Cub_Vol))
    print('##############    CUBOID OPERATIONS    ################')
    length = float(input('Enter Length of Cuboid : '))
    breadth = float(input('Enter the Breadth of Cuboid : '))
    height = float(input('Enter the Height of Cuboid : '))
    Cubo = Cuboid(length,breadth,height)
    print('Length of Cuboid = ', Cubo.length)
    print('Breadth of Cuboid = ', Cubo.breadth)
    print('Height of Cuboid = ', Cubo.height)
    Cubo_Cur_area = Cubo.Curved_Area()
    print('Curved Area of the Cuboid is {:.2f}'.format(Cubo_Cur_area))
    Cubo_Tot_area = Cubo.Total_Area()
    print('Total Surface Area of the Cuboid is {:.2f}'.format(Cubo_Tot_area))
    Cubo_Vol = Cubo.Volume()
    print('Volume of Cuboid is {:.2f}'.format(Cubo_Vol))
    print('##############    CYLINDER OPERATIONS    ################')
    Radius = float(input('Enter Radius : '))
    height = float(input('Enter the Height of Cylinder : '))
    Cy = Cylinder(Radius,height)
    print('Radius of Cylinder = ', Cy.Radius)
    print('Height of Cylinder = ', Cy.height)
    Cy_Cur_area = Cy.Curved_Area()
    print('Curved Area of the Cylinder is {:.2f}'.format(Cy_Cur_area))
    Cy_Tot_area = Cy.Total_Area()
    print('Total Surface Area of the Cuboid is {:.2f}'.format(Cy_Tot_area))
    Cy_Vol = Cy.Volume()
    print('Volume of Cylinder is {:.2f}'.format(Cy_Vol))
    print('##############    CONE OPERATIONS    ################')
    Radius = float(input('Enter Radius : '))
    height = float(input('Enter the Height of Cone : '))
    Con = Cone(Radius,height)
    print('Radius of Cone = ', Con.Radius)
    print('Height of Cone = ', Con.height)
    Con_Cur_area = Con.Curved_Area()
    print('Curved Area of the Cone is {:.2f}'.format(Con_Cur_area))
    Con_Tot_area = Con.Total_Area()
    print('Total Surface Area of the Cone is {:.2f}'.format(Con_Tot_area))
    Con_Vol = Con.Volume()
    print('Volume of Cone is {:.2f}'.format(Con_Vol))
    print('##############    FRUSTUM_CONE OPERATIONS    ################')
    Radius1 = float(input('Enter Radius 1 : '))
    Radius2 = float(input('Enter Radius 2 : '))
    height = float(input('Enter the Height of Cone : '))
    F_Con = Frustum_Cone(Radius1,Radius2,height)
    print('Radius 1 of Frustum of Cone = ', F_Con.Radius1)
    print('Radius 2 of Frustum of Cone = ', F_Con.Radius2)
    print('Height of Cone = ', Con.height)
    F_Con_Cur_area = F_Con.Curved_Area()
    print('Curved Area of Frustum of Cone is {:.2f}'.format(F_Con_Cur_area))
    F_Con_Tot_area = F_Con.Total_Area()
    print('Total Surface Area of Frustum of Cone is {:.2f}'.format(F_Con_Tot_area))
    F_Con_Vol = F_Con.Volume()
    print('Volume of Frustum of Cone is {:.2f}'.format(F_Con_Vol))
    print('##############      SPHERE OPERATIONS    ################')
    Radius = float(input('Enter Radius : '))
    SP = Sphere(Radius)
    print('Radius of Sphere = ', SP.Radius)
    SP_Tot_area = SP.Total_Area()
    print('Total Surface Area of Sphere is {:.2f}'.format(SP_Tot_area))
    SP_Vol = SP.Volume()
    print('Volume of Sphere is {:.2f}'.format(SP_Vol))
    print('##############      HEMI-SPHERE OPERATIONS    ################')
    Radius = float(input('Enter Radius : '))
    HS = H_Sphere(Radius)
    print('Radius of HemiSphere = ', HS.Radius)
    HS_Cur_area = HS.Curved_Area()
    print('Curved Surface Area of HemiSphere is {:.2f}'.format(HS_Cur_area))
    HS_Tot_area = HS.Total_Area()
    print('Total Surface Area of HemiSphere is {:.2f}'.format(HS_Tot_area))
    HS_Vol = HS.Volume()
    print('Volume of HemiSphere is {:.2f}'.format(HS_Vol))

if __name__ == '__main__':
    main()